### PR TITLE
Move pap-AW and pap-CW out of the iso-639-2 folder since they don't work. Also updated translations

### PR DESCRIPTION
**Pull request by acesuares**

### CODE REVIEW

**Comment by kuroda** [comment]
Ah, you have submitted #793.

I will see this problem.

**Comment by acesuares** [comment]
Is there any progress?

**Comment by acesuares** [comment]
I really don't know why the tests keep failing. I checked if my files used the same keys as the en.yml but still there's this error. Please help! @tigrish 

````
Failures:
  1) a rails-i18n rails/locale/pap-AW.yml locale file should not have missing particular pluralization keys
     Failure/Error:
       keys = @locale_file.missing_pluralization_keys.reject do |key, value|
         key.match(/\.errors\.messages\.restrict_dependent_destroy$/)
       end
     
     NoMethodError:
       undefined method `plural_rule_names' for nil:NilClass
     # ./vendor/bundle/ruby/2.5.0/gems/i18n-spec-0.6.0/lib/i18n-spec/models/locale_file.rb:58:in `missing_pluralization_keys'
     # ./spec/unit/matchers/have_missing_particular_pluralization_keys_matcher.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/unit/translation_spec.rb:19:in `block (3 levels) in <top (required)>'
Finished in 0.88725 seconds (files took 0.32968 seconds to load)
1968 examples, 1 failure
Failed examples:
rspec ./spec/unit/translation_spec.rb[18:7] # a rails-i18n rails/locale/pap-AW.yml locale file should not have missing particular pluralization keys
/home/travis/.rvm/rubies/ruby-2.5.0/bin/ruby -I/home/travis/build/svenfuchs/rails-i18n/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib:/home/travis/build/svenfuchs/rails-i18n/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.7.1/lib /home/travis/build/svenfuchs/rails-i18n/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/exe/rspec spec/unit/pluralization_spec.rb spec/unit/translation_spec.rb spec/unit/transliteration_spec.rb failed
````

**Comment by acesuares** [comment]
Dear all, I think I have added the pluralization files, but still the test fails. Could anyone give a hint on what is wrong? This all works perfect in production, by the way.

**Comment by acesuares** [comment]
I dont' see the difference in en.yml
```
        restrict_dependent_destroy:
          has_one: Cannot delete record because a dependent %{record} exists
          has_many: Cannot delete record because dependent %{record} exist
```
or in pap-CW.yml
```
        restrict_dependent_destroy:
          has_one: "No por kita e registro akí pasobra un otro %{record} ta dependé di dje"
          has_many: "No por kita e registro akí pasobra otro %{record} ta dependé di dje"

```
But still the error is
``` 1) a rails-i18n rails/locale/pap-CW.yml locale file should not have missing particular pluralization keys
     Failure/Error:
       keys = @locale_file.missing_pluralization_keys.reject do |key, value|
         key.match(/\.errors\.messages\.restrict_dependent_destroy$/)
       end
     NoMethodError:
       undefined method `plural_rule_names' for nil:NilClass
```

**Comment by acesuares** [comment]
Is this related to the ONLY other Google entry I could find: https://github.com/svenfuchs/rails-i18n/issues/570 ?
It says that the problem was the name of the file.

**Comment by kuroda** [comment]
@acesuares 

I fixed a matcher causing your failure with https://github.com/svenfuchs/rails-i18n/commit/57dd7488a67921900408a89b0646d78f797d5c09.

Please merge this commit.

**Comment by acesuares** [comment]
So why do we not have a LocaleFile? Should we have one? Thanks for fixing!!!!!

**Comment by kuroda** [comment]
> So why do we not have a LocaleFile? Should we have one? 

You have a LocaleFile, but your LocaleFile is missing `language` information.

This information comes from [iso](https://github.com/Locale/iso) gem.

This way you can see the situation:

```
$ gem install iso
$ irb
irb> require 'iso'
irb> ISO::Tag.new('pt-BR').language
=> #<ISO::Language:0x00005600d1e5dd50 @plural_rule_names=["one", "other"], @direction="ltr", @code="pt", @options={}>
irb> ISO::Tag.new('pap-AW').language
=> nil
```

You might have to make a PR to this gem.

**Comment by acesuares** [comment]
Thanks again!
I've been trying to get pap in there as a language but it only takes two letter languages.
https://github.com/Locale/iso/pull/10
